name: Frontend CI/CD
on:
  push:
    branches:
      - main
jobs:
  build-and-deploy:
    runs-on: self-hosted
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20'
    - name: Install dependencies
      run: npm install --legacy-peer-deps
    - name: Create .env file
      run: |
        echo "NEXT_PUBLIC_API_URL=${{ secrets.NEXT_PUBLIC_API_URL }}" >> .env
        echo "SECRET_KEY=${{ secrets.SECRET_KEY }}" >> .env
    - name: Build Next.js App
      run: npm run build
    - name: Archive app bundle
      run: tar -czf app.tar.gz .next node_modules package.json package-lock.json .env public
    - name: Upload to EC2
      uses: appleboy/scp-action@v0.1.4
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USER }}
        key: ${{ secrets.EC2_SSH_KEY }}
        source: "app.tar.gz"
        target: "/var/www/my-next-app/"
    - name: SSH and Deploy on EC2
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USER }}
        key: ${{ secrets.EC2_SSH_KEY }}
        script: |
          cd /var/www/my-next-app
          tar -xzf app.tar.gz
          rm app.tar.gz
          npm install --production
          pm2 start npm --name "my-next-app" -- start || pm2 restart "my-next-app"
          pm2 save








        
        
          

  
          


